import { KeysOf } from "../utils/common";

export enum ExoticMissions {
	Avalon,
	Harbinger,
	Presage,
	SeraphsShield,
	Starcrossed,
	TheWhisper,
	VoxObscura,
	ZeroHour,
}
export enum Raids {
	CrotasEnd,
	CrownOfSorrow,
	DeepStoneCrypt,
	GardenOfSalvation,
	KingsFall,
	LastWish,
	Leviathan,
	LeviathanEaterOfWorlds,
	LeviathanSpireOfStars,
	Pantheon,
	PhanteonAtraksSovereign,
	PhanteonNezarecSublime,
	PhanteonOryxExalted,
	PhanteonRhulkIndomitable,
	RootOfNightmares,
	SalvationsEdge,
	ScourgeOfThePast,
	VaultOfGlass,
	VowOfTheDisciple,
}
export enum Dungeons {
	Duality,
	GhostsOfTheDeep,
	GraspOfAvarice,
	PitOfHeresy,
	Prophecy,
	SpireOfTheWatcher,
	TheShatteredThrone,
	WarlordsRuin,
}
export enum ScoredNightFalls {
	AGardenWorld,
	BattlegroundBehemoth,
	BattlegroundFoothold,
	BattlegroundHailstone,
	BattlegroundOracle,
	BirthplaceOfTheVile,
	Broodhold,

	ExodusCrash,
	FallenSABER,

	HeistBattlegroundEuropa,
	HeistBattlegroundMars,
	HeistBattlegroundMoon,
	HyperNetCurrent,
	LakeOfShadows,
	LegendPsiOpsBattlegroundCosmodrome,

	ProvingGrounds,
	PsiOpsBattlegroundEDZ,
	PsiOpsBattlegroundMoon,

	SavathunsSong,
	StrangeTerrain,
	TheArmsDealer,
	TheCorrupted,
	TheDevilsLair,
	TheDisgraced,
	TheFesteringCore,
	TheGlassway,
	TheHollowedLair,
	TheInsightTerminus,
	TheInvertedSpire,
	TheLightblade,
	TheScarletKeep,
	TreeOfProbabilities,
	WardenOfNothing,
}

// export enum DestinyActivity {
// 	Avalon,
// 	Harbinger,
// 	Presage,
// 	SeraphsShield,
// 	Starcrossed,
// 	TheWhisper,
// 	VoxObscura,
// 	ZeroHour,

// 	CrotasEnd,
// 	CrownOfSorrow,
// 	DeepStoneCrypt,
// 	GardenOfSalvation,
// 	KingsFall,
// 	LastWish,
// 	Leviathan,
// 	LeviathanEaterOfWorlds,
// 	LeviathanSpireOfStars,
// 	Pantheon,
// 	PhanteonAtraksSovereign,
// 	PhanteonNezarecSublime,
// 	PhanteonOryxExalted,
// 	PhanteonRhulkIndomitable,
// 	RootOfNightmares,
// 	SalvationsEdge,
// 	ScourgeOfThePast,
// 	VaultOfGlass,
// 	VowOfTheDisciple,

// 	Duality,
// 	GhostsOfTheDeep,
// 	GraspOfAvarice,
// 	PitOfHeresy,
// 	Prophecy,
// 	SpireOfTheWatcher,
// 	TheShatteredThrone,
// 	WarlordsRuin,

// 	AGardenWorld,
// 	BattlegroundBehemoth,
// 	BattlegroundFoothold,
// 	BattlegroundHailstone,
// 	BattlegroundOracle,
// 	BirthplaceOfTheVile,
// 	Broodhold,
// 	ExodusCrash,
// 	FallenSABER,
// 	HeistBattlegroundEuropa,
// 	HeistBattlegroundMars,
// 	HeistBattlegroundMoon,
// 	HyperNetCurrent,
// 	LakeOfShadows,
// 	LegendPsiOpsBattlegroundCosmodrome,
// 	ProvingGrounds,
// 	PsiOpsBattlegroundEDZ,
// 	PsiOpsBattlegroundMoon,
// 	SavathunsSong,
// 	StrangeTerrain,
// 	TheArmsDealer,
// 	TheCorrupted,
// 	TheDevilsLair,
// 	TheDisgraced,
// 	TheFesteringCore,
// 	TheGlassway,
// 	TheHollowedLair,
// 	TheInsightTerminus,
// 	TheInvertedSpire,
// 	TheLightblade,
// 	TheScarletKeep,
// 	TreeOfProbabilities,
// 	WardenOfNothing,
// }

export const DestinyActivity = {
	...Dungeons,
	...Raids,
	...ScoredNightFalls,
	...ExoticMissions,
};

export type DestinyActivity = Dungeons | Raids | ScoredNightFalls | ExoticMissions ;

//export const DestinyActivity = { ...ExoticMissions, ...Raids, ...Dungeons, ...ScoredNightFalls };
//export const DestinyActivity = Object.assign({}, ExoticMissions, Raids, Dungeons, ScoredNightFalls); // also work
//export type DestinyActivity = ExoticMissions | Raids | Dungeons | ScoredNightFalls;

//export type DestinyActivity =  (typeof ExoticMissions) &  (typeof Raids) &  (typeof Dungeons) &  (typeof ScoredNightFalls);// & { ...ExoticMissions, ...Raids, ...Dungeons, ...ScoredNightFalls };
