import { DestinyActivity } from "../enums/DestinyActivity";
import { ModeType } from "../enums/ModeType";

export const ModeTypeEN: { [key in keyof typeof  ModeType]: string; } = {
	Grandmaster: "Grandmaster",
	Normal: "Normal",
	Legend: "Legend",
	Master: "Master",
	Contest: "Contest",
	Prestige: "Prestige",
	NormalLegacy: "Normal (Legacy)",
	Other: "Other",
	Guided: "Guided Games",
	Heroic: "Heroic",
};


export const activitiesEN: { [key in keyof typeof DestinyActivity]: string;  } = {
	AGardenWorld: "A Garden World",
	Avalon: "//node.ovrd.AVALON//",
	BattlegroundBehemoth: "Battleground: Behemoth",
	BattlegroundFoothold: "Battleground: Foothold",
	BattlegroundHailstone: "Battleground: Hailstone",
	BattlegroundOracle: "Battleground: Oracle",
	BirthplaceOfTheVile: "Birthplace of the Vile",
	Broodhold: "Broodhold",
	CrotasEnd: "Crota's End",
	CrownOfSorrow: "Crown of Sorrow",
	DeepStoneCrypt: "Deep Stone Crypt",
	Duality: "Duality",
	ExodusCrash: "Exodus Crash",
	FallenSABER: "Fallen S.A.B.E.R.",
	GardenOfSalvation: "Garden of Salvation",
	GhostsOfTheDeep: "Ghosts of the Deep",
	GraspOfAvarice: "Grasp Of Avarice",
	Harbinger: "Harbinger",
	HeistBattlegroundEuropa: "Heist Battleground: Europa",
	HeistBattlegroundMars: "Heist Battleground: Mars",
	HeistBattlegroundMoon: "Heist Battleground: Moon",
	HyperNetCurrent: "HyperNet Current",
	KingsFall: "King's Fall",
	LakeOfShadows: "Lake of Shadows",
	LastWish: "Last Wish",
	LegendPsiOpsBattlegroundCosmodrome: "Legend PsiOps Battleground: Cosmodrome",
	Leviathan: "Leviathan",
	LeviathanEaterOfWorlds: "Leviathan, Eater of Worlds",
	LeviathanSpireOfStars: "Leviathan, Spire of Stars",
	SeraphsShield: "Operation: Seraph's Shield",
	Pantheon: "The Pantheon",
	PhanteonAtraksSovereign: "The Pantheon: Atraks Sovereign",
	PhanteonNezarecSublime: "The Pantheon: Nezarec Sublime",
	PhanteonOryxExalted: "The Pantheon: Oryx Exalted",
	PhanteonRhulkIndomitable: "The Inverted Spire",
	PitOfHeresy: "Pit Of Heresy",
	Presage: "Presage",
	Prophecy: "Prophecy",
	ProvingGrounds: "Proving Grounds",
	PsiOpsBattlegroundEDZ: "PsiOps Battleground: EDZ",
	PsiOpsBattlegroundMoon: "PsiOps Battleground: Moon",
	RootOfNightmares: "Root of Nightmares",
	SalvationsEdge: "Salvations Edge",
	SavathunsSong: "Savathûn's Song",
	ScourgeOfThePast: "Scourge of the Past",
	SpireOfTheWatcher: "SpireOfTheWatcher",
	Starcrossed: "Starcrossed",
	StrangeTerrain: "Strange Terrain",
	TheArmsDealer: "The Arms Dealer",
	TheCorrupted: "The Corrupted",
	TheDevilsLair: "The Devils' Lair",
	TheDisgraced: "The Disgraced",
	TheFesteringCore: "The Festering Core",
	TheGlassway: "The Glassway",
	TheHollowedLair: "The Hollowed Lair",
	TheInsightTerminus: "The Insight Terminus",
	TheInvertedSpire: "The Inverted Spire",
	TheLightblade: "The Inverted Spire",
	TheScarletKeep: "The Scarlet Keep",
	TheShatteredThrone: "The Shattered Throne",
	TheWhisper: "The Whisper",
	TreeOfProbabilities: "Tree of Probabilities",
	VaultOfGlass: "Vault of Glass",
	VowOfTheDisciple: "Vow of the Disciple",
	VoxObscura: "Vox Obscura",
	WardenOfNothing: "Warden of Nothing",
	WarlordsRuin: "Warlord's Ruin",
	ZeroHour: "Zero Hour",
};
