import { DestinyActivity, Dungeons, ExoticMissions, Raids, ScoredNightFalls } from "../enums/DestinyActivity";
import { ModeType } from "../enums/ModeType";

export const ModeTypeEN: { [key in keyof typeof ModeType]: string } = {
	Grandmaster: "Grandmaster",
	Normal: "Normal",
	Legend: "Legend",
	Master: "Master",
	Contest: "Contest",
	Prestige: "Prestige",
	NormalLegacy: "Normal (Legacy)",
	Other: "Other",
	Guided: "Guided Games",
	Heroic: "Heroic",
};

export const DungeonsEn: { [key in keyof typeof Dungeons]: string } = {
	Duality: "Duality",
	GhostsOfTheDeep: "Ghosts of the Deep",
	GraspOfAvarice: "Grasp Of Avarice",
	PitOfHeresy: "Pit Of Heresy",
	Prophecy: "Prophecy",
	SpireOfTheWatcher: "SpireOfTheWatcher",
	TheShatteredThrone: "The Shattered Throne",
	WarlordsRuin: "Warlord's Ruin",
};
export const RaidsEn: { [key in keyof typeof Raids]: string } = {
	CrotasEnd: "Crota's End",
	CrownOfSorrow: "Crown of Sorrow",
	DeepStoneCrypt: "Deep Stone Crypt",
	GardenOfSalvation: "Garden of Salvation",
	KingsFall: "King's Fall",
	LastWish: "Last Wish",
	Leviathan: "Leviathan",
	LeviathanEaterOfWorlds: "Leviathan, Eater of Worlds",
	LeviathanSpireOfStars: "Leviathan, Spire of Stars",
	Pantheon: "The Pantheon",
	PhanteonAtraksSovereign: "The Pantheon: Atraks Sovereign",
	PhanteonNezarecSublime: "The Pantheon: Nezarec Sublime",
	PhanteonOryxExalted: "The Pantheon: Oryx Exalted",
	PhanteonRhulkIndomitable: "The Inverted Spire",
	RootOfNightmares: "Root of Nightmares",
	SalvationsEdge: "Salvations Edge",
	ScourgeOfThePast: "Scourge of the Past",
	VaultOfGlass: "Vault of Glass",
	VowOfTheDisciple: "Vow of the Disciple",
};
export const ScoredNightFallsEn: { [key in keyof typeof ScoredNightFalls]: string } = {
	AGardenWorld: "A Garden World",
	BattlegroundBehemoth: "Battleground: Behemoth",
	BattlegroundFoothold: "Battleground: Foothold",
	BattlegroundHailstone: "Battleground: Hailstone",
	BattlegroundOracle: "Battleground: Oracle",
	BirthplaceOfTheVile: "Birthplace of the Vile",
	Broodhold: "Broodhold",
	DefiantBattlegroundCosmodrome: "Defiant Battleground: Cosmodrome",
	DefiantBattlegroundEDZ: "Defiant Battleground: EDZ",
	DefiantBattlegroundOrbitalPrison: "Defiant Battleground: Orbital Prison",
	ExodusCrash: "Exodus Crash",
	FallenSABER: "Fallen S.A.B.E.R.",
	HeistBattlegroundEuropa: "Heist Battleground: Europa",
	HeistBattlegroundMars: "Heist Battleground: Mars",
	HeistBattlegroundMoon: "Heist Battleground: Moon",
	HyperNetCurrent: "HyperNet Current",
	LakeOfShadows: "Lake of Shadows",
	Liminality: "Liminality",
	LegendPsiOpsBattlegroundCosmodrome: "Legend PsiOps Battleground: Cosmodrome",
	ProvingGrounds: "Proving Grounds",
	PsiOpsBattlegroundEDZ: "PsiOps Battleground: EDZ",
	PsiOpsBattlegroundMoon: "PsiOps Battleground: Moon",
	SavathunsSong: "Savathûn's Song",
	StrangeTerrain: "Strange Terrain",
	TheArmsDealer: "The Arms Dealer",
	TheCorrupted: "The Corrupted",
	TheDevilsLair: "The Devils' Lair",
	TheDisgraced: "The Disgraced",
	TheFesteringCore: "The Festering Core",
	TheGlassway: "The Glassway",
	TheHollowedLair: "The Hollowed Lair",
	TheInsightTerminus: "The Insight Terminus",
	TheInvertedSpire: "The Inverted Spire",
	TheLightblade: "The Inverted Spire",
	TheScarletKeep: "The Scarlet Keep",
	TreeOfProbabilities: "Tree of Probabilities",
	WardenOfNothing: "Warden of Nothing",
};
export const ExoticMissionsEn: { [key in keyof typeof ExoticMissions]: string } = {
	Avalon: "//node.ovrd.AVALON//",
	Harbinger: "Harbinger",
	SeraphsShield: "Operation: Seraph's Shield",
	Presage: "Presage",
	Starcrossed: "Starcrossed",
	TheWhisper: "The Whisper",
	VoxObscura: "Vox Obscura",
	ZeroHour: "Zero Hour",
};

export const activitiesEN: { [key in keyof typeof DestinyActivity]: string } = { ...DungeonsEn, ...RaidsEn, ...ScoredNightFallsEn, ...ExoticMissionsEn };

export const ranksEN: {[key in number]: string} ={
	0:"Unranked",
	1:"New Light",
	2:"Explorer",
	3:"Initiate",
	4:"Scout",
	5:"Adventurer",
	6:"Veteran",
	7:"Elite",
	8:"Justicar",
	9:"Vanquisher",
	10:"Exemplar",
	11:"Paragon",

}