export enum DestinyRaid {
	Leviathan = 0,
	LeviathanEaterOfWorlds,
	LeviathanSpireOfStars,
	LastWish,
	ScourgeOfThePast,
	CrownOfSorrow,
	GardenOfSalvation,
	DeepStoneCrypt,
	VaultOfGlass,
	VowOfTheDisciple,
	KingsFall,
	RootOfNightmares,
	CrotasEnd,
	Pantheon,
	PhanteonAtraksSovereign,
	PhanteonOryxExalted,
	PhanteonRhulkIndomitable,
	PhanteonNezarecSublime,
	SalvationsEdge,
}

export enum DestinyDungeon {
	TheShatteredThrone = 100,
	PitOfHeresy,
	Prophecy,
	GraspOfAvarice,
	Duality,
	SpireOfTheWatcher,
	GhostsOfTheDeep,
	WarlordsRuin,
}

export enum DestinyExoticMission {
	TheWhisper = 200,
	ZeroHour,
	Harbinger,
	Presage,
	VoxObscura,
	SeraphsShield,
	Avalon,
	Starcrossed,
	Excision,
	DualDestiny,
}

export enum DestinyGrandMasterNightFall {
	AGardenWorld = 300,
	BattlegroundBehemoth,
	BattlegroundFoothold,
	BattlegroundHailstone,
	BattlegroundOracle,
	BirthplaceOfTheVile,
	Broodhold,
	DefiantBattlegroundCosmodrome,
	DefiantBattlegroundEDZ,
	DefiantBattlegroundOrbitalPrison,
	ExodusCrash,
	FallenSABER,
	HeistBattlegroundEuropa,
	HeistBattlegroundMars,
	HeistBattlegroundMoon,
	HyperNetCurrent,
	LakeOfShadows,
	LegendPsiOpsBattlegroundCosmodrome,
	Liminality,
	ProvingGrounds,
	PsiOpsBattlegroundEDZ,
	PsiOpsBattlegroundMoon,
	SavathunsSong,
	StrangeTerrain,
	TheArmsDealer,
	TheCorrupted,
	TheDevilsLair,
	TheDisgraced,
	TheFesteringCore,
	TheGlassway,
	TheHollowedLair,
	TheInsightTerminus,
	TheInvertedSpire,
	TheLightblade,
	TheScarletKeep,
	TreeOfProbabilities,
	WardenOfNothing,
}

export const ActiveScoredNightFalls = [
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.TheGlassway] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.WardenOfNothing] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.TheDisgraced] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.FallenSABER] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.Liminality] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.ExodusCrash] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.DefiantBattlegroundCosmodrome] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.TheInsightTerminus] as keyof typeof DestinyGrandMasterNightFall,
	DestinyGrandMasterNightFall[DestinyGrandMasterNightFall.TheDevilsLair] as keyof typeof DestinyGrandMasterNightFall,
];

export const DestinyActivity = {
	...DestinyRaid,
	...DestinyDungeon,
	...DestinyExoticMission,
	...DestinyGrandMasterNightFall,
};

export type DestinyActivity = DestinyDungeon | DestinyRaid | DestinyGrandMasterNightFall | DestinyExoticMission;
